config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :text_posts, except: [:index]
  resources :link_posts, except: [:index]

  resources :posts, only: [:index] do
    resources :votes, controller: "post_votes"
    resources :comments, only: [:create, :destroy]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :user, presence: true
  validates :text, presence: true

  after_save :send_new_comment_mailer

  def send_new_comment_mailer
    NotificationsMailer.new_comment(self.post.user, self).deliver_later
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Link post was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to comments_url, notice: 'Comment was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :post_id, :text)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<p id="comment_<%= comment.id %>"><%= comment.text %></p>

app/views/comments/_comments.html.erb
<div id="comments">
  <% post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for comment, url: post_comments_path(post), remote: true do |f| %>
  <%= render 'shared/error_messages', resource: comment %>

  <div class="field">
    <strong>Add a comment:</strong>
    <%= f.text_area :text %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.valid? %>
  $('#new_comment').html('<%=j render 'form', post: @post, comment: Comment.new %>');
  $('#comments').append('<%= j render @comment %>');
  $('#comment_<%= @comment.id %>').effect('highlight', 'slow');
<% else %>
  $('#new_comment').html('<%=j render 'form', post: @post, comment: @comment %>');
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Permalink</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.permalink %></td>
        <td><%= comment.text %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Permalink:</strong>
  <%= @comment.permalink %>
</p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>