config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :text_posts, except: [:index]
  resources :link_posts, except: [:index]

  resources :posts, only: [:index] do
    resources :votes, controller: "post_votes"
    resources :comments, only: [:create, :destroy]
  end
end

app/models/link_post.rb
class LinkPost < Post
  validates :url, presence: true
end

app/controllers/link_posts_controller.rb
class LinkPostsController < ApplicationController
  before_action :set_link_post, only: [:edit, :update, :destroy]

  def show
    @link_post = LinkPost.find(params[:id])
  end

  def new
    @link_post = LinkPost.new
  end

  def edit
  end

  def create
    @link_post = LinkPost.new(link_post_params)
    @link_post.user = current_user

    respond_to do |format|
      if @link_post.save
        format.html { redirect_to @link_post, notice: 'Link post was successfully created.' }
        format.json { render :show, status: :created, location: @link_post }
      else
        format.html { render :new }
        format.json { render json: @link_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @link_post.update(link_post_params)
        format.html { redirect_to @link_post, notice: 'Link post was successfully updated.' }
        format.json { render :show, status: :ok, location: @link_post }
      else
        format.html { render :edit }
        format.json { render json: @link_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @link_post.destroy
    respond_to do |format|
      format.html { redirect_to link_posts_url, notice: 'Link post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link_post
      @link_post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_post_params
      params.require(:link_post).permit(:title, :url)
    end
end

app/views/link_posts/_form.html.erb
<%= form_for(@link_post) do |f| %>
  <%= render 'shared/error_messages', :resource => @link_post %>


  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :url %>
    <%= f.url_field :url %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/link_posts/edit.html.erb
<h1>Editing Link Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @link_post %> |
<%= link_to 'Back', posts_path %>

app/views/link_posts/new.html.erb
<h1>New Link Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/link_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link_post.title %>
</p>

<% if current_user == @link_post.user %>
  <%= link_to 'Edit', edit_link_post_path(@link_post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

<%= render 'comments/form', post: @link_post, comment: Comment.new %>

<%= render 'comments/comments', post: @link_post %>