config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :text_posts, except: [:index]
  resources :link_posts, except: [:index]

  resources :posts, only: [:index] do
    resources :votes, controller: "post_votes"
    resources :comments, only: [:create, :destroy]
  end
end

app/models/text_post.rb
class TextPost < Post
  validates :text, presence: true
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  before_action :set_text_post, only: [:edit, :update, :destroy]

  # GET /text_posts/1
  # GET /text_posts/1.json
  def show
    @text_post = TextPost.find(params[:id])
  end

  # GET /text_posts/new
  def new
    @text_post = TextPost.new
  end

  # GET /text_posts/1/edit
  def edit
  end

  # POST /text_posts
  # POST /text_posts.json
  def create
    @text_post = TextPost.new(text_post_params)
    @text_post.user = current_user

    respond_to do |format|
      if @text_post.save
        format.html { redirect_to @text_post, notice: 'Text post was successfully created.' }
        format.json { render :show, status: :created, location: @text_post }
      else
        format.html { render :new }
        format.json { render json: @text_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_posts/1
  # PATCH/PUT /text_posts/1.json
  def update
    respond_to do |format|
      if @text_post.update(text_post_params)
        format.html { redirect_to @text_post, notice: 'Text post was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_post }
      else
        format.html { render :edit }
        format.json { render json: @text_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_posts/1
  # DELETE /text_posts/1.json
  def destroy
    @text_post.destroy
    respond_to do |format|
      format.html { redirect_to text_posts_url, notice: 'Text post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_post
      @text_post = current_user.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_post_params
      params.require(:text_post).permit(:title, :url, :text)
    end
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/views/text_posts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.downcase.humanize %> from being saved:</h2>

    <ul>
    <% resource.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/text_posts/_form.html.erb
<%= form_for(@text_post) do |f| %>
  <%= render 'shared/error_messages', :resource => @text_post %>

  <fieldset>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </fieldset>

  <fieldset>
    <%= f.label :url %>
    <%= f.url_field :url %>
  </fieldset>

  <fieldset>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </fieldset>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_posts/edit.html.erb
<h1>Editing Text Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_post %> |
<%= link_to 'Back', text_posts_path %>

app/views/text_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Text Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_posts.each do |text_post| %>
      <tr>
        <td><%= link_to 'Show', text_post %></td>
        <td><%= link_to 'Edit', edit_text_post_path(text_post) %></td>
        <td><%= link_to 'Destroy', text_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text post', new_text_post_path %>

app/views/text_posts/new.html.erb
<h1>New Text Post</h1>

<%= render 'form' %>

<%= link_to 'Back', text_posts_path %>

app/views/text_posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @text_post.title %>
</p>

<p>
  <%= markdown @text_post.text %>
</p>

<% if current_user == @text_post.user %>
  <%= link_to 'Edit', edit_text_post_path(@text_post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

<%= render 'comments/form', post: @text_post, comment: Comment.new %>

<%= render 'comments/comments', post: @text_post %>