config/routes.rb
Rails.application.routes.draw do
  root to: "posts#index"

  resources :text_posts, except: [:index]
  resources :link_posts, except: [:index]

  resources :posts, only: [:index] do
    resources :votes, controller: "post_votes"
    resources :comments, only: [:create, :destroy]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :votes, as: :votable
  has_many :comments

  validates :user, presence: true
  validates :title, presence: true

  def vote_by(user)
    @vote_by ||= votes.where(user_id: user.id).limit(1).first
  end

  def score
    votes.sum(:score)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<hr/>

<p>
  <%= link_to "Submit a new text post", new_text_post_path %>
  <br/>
  <%= link_to "Submit a new link", new_link_post_path %>
</p>

<hr/>

<table width="800px">
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td>
          <%= post.score %>
          <%= link_to post.title, post %>
        </td>
        <td>
          <%= post.user.email %>
        </td>
        <td>
          <% vote = post.vote_by(current_user) %>
          <% if vote.present? %>
            <%= "You voted:" %>
            <%= (vote.score > 0 ? "Good" : "Bad") %>
          <% else %>
            <%= link_to "Up Vote", post_votes_path(post, score: 1), method: :post %>
            or
            <%= link_to "Down Vote", post_votes_path(post, score: -1), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><%#= link_to 'New Post', new_post_path %></p>